export default {
  RECIEVED_ROLES: 'RECIEVED_ROLES',
  ROLE_SELECTED: 'ROLE_SELECTED',
  ROLES_CLEARED: 'ROLES_CLEARED',
  SELECTED_ROLE_CLEARED: 'SELECTED_ROLE_CLEARED',
  RECIEVED_ERROR: 'RECIEVED_ROLE_ERROR'
};
