export default {
  RECIEVED_APPLICATIONS: 'RECIEVED_APPLICATIONS',
  OPEN_CREATE_APPLICATION: 'OPEN_CREATE_APPLICATION',
  CLOSE_CREATE_APPLICATION: 'CLOSE_CREATE_APPLICATION',
  SET_SELECTED_APP: 'SET_SELECTED_APP',
  RECIEVED_APP_ERROR: 'RECIEVED_APP_ERROR',
  IS_LOADING: 'IS_LOADING'
};
