export default {
  RECIEVED_SCOPES: 'RECIEVED_SCOPES',
  RECIEVED_ASSIGNED_SCOPES: 'RECIEVED_ASSIGNED_SCOPES',
  ASSIGNED_SCOPES_CLEARED: 'ASSIGNED_SCOPES_CLEARED',
  RECIEVED_ERROR: 'RECIEVED_SCOPE_ERROR'
};
